### ISSUE TITLE
Display Changelog Tab for Specific Pages/Stories

### ISSUE THREAD

**Issue by dezireeteague** [DaveBitter/storybook-addon-changelog-viewer#1]
I added the Storybook changelog viewer to my project and I noticed that the `Changelog` tab is persistent. My issue is that the log is only populated on the doc page and not the other pages/stories within the same component folder. Is it possible to make the changelog tab display only on a specific page? If not, how can I make the log render on all the other pages/stories for a consistent experience?

**Change log is empty on "How to install"** ❌
![Screenshot 2023-10-10 at 11 54 43 AM](https://github.com/DaveBitter/storybook-addon-changelog-viewer/assets/135263238/179763e3-eecc-4917-b7c1-e10d8dfd09ff)

**Change log renders on "Docs"** ✅
![Screenshot 2023-10-10 at 11 55 03 AM](https://github.com/DaveBitter/storybook-addon-changelog-viewer/assets/135263238/0d60b847-a3ff-4f9e-8b4f-0c57cff26452)

**Change log tab appears on "Examples"** ❌
![Screenshot 2023-10-10 at 11 59 08 AM](https://github.com/DaveBitter/storybook-addon-changelog-viewer/assets/135263238/b5003156-bcbf-46e3-b8fa-cb1b1975e07e)

**Change log disappears after clicking tab from "Examples"** ❌
![Screenshot 2023-10-10 at 11 55 25 AM](https://github.com/DaveBitter/storybook-addon-changelog-viewer/assets/135263238/3668c3e5-d7bb-4acd-a862-6a03ec177326)

Looking at the source code manager.js file, I'm wondering if there's a way to manipulate the addon object `match` or `render` to resolve this issue?
![Screenshot 2023-10-10 at 12 04 47 PM](https://github.com/DaveBitter/storybook-addon-changelog-viewer/assets/135263238/7d94f750-a509-4ea0-bb29-0f3155f4bd9e)

**Comment by BrendanThysse** [comment]
How come this issue is close as not planned? It is more a bug than a feature as having the tab on Pages/Stories where nothing is being rendered is a horrible user experience?
